version: "3.8"
services:
  # 2. Redis - In-Memory Cache & Queue
  redis:
    image: redis:7-alpine
    container_name: pomeloec_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

  # 3. Message Broker (Kafka chuẩn KRaft mới, không cần Zookeeper)
  kafka:
    image: apache/kafka:3.7.0
    container_name: pomeloec_kafka
    user: "root"
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_data:/tmp/kafka-logs
    restart: always

  # 4. Identity & Access Management (SSO OIDC Server)
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: pomeloec_keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    restart: always

  # 5. Change Data Capture (CDC Connector)
  debezium:
    image: quay.io/debezium/connect:2.5
    container_name: pomeloec_debezium
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      - kafka
    restart: always

  # 6. Analytics Database (OLAP)
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: pomeloec_clickhouse
    ports:
      - "8123:8123" # HTTP Port
      - "9000:9000" # Native Client Port
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: always

  # 7. Phân tích Tìm kiếm (Full-Text Search Engine)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: pomeloec_elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: always

volumes:
  redis_data:
  kafka_data:
  clickhouse_data:
  elasticsearch_data:
